data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "insipx"
public_key = "6274199fd286efcd04b0234aec390311f312a3af78c3917f8280d16597f40d2a"

[[chains]]
name = "parallel"
rpc_endpoints = [
    'wss://rpc.parallel.fi',
    'wss://parallel.api.onfinality.io/public-ws',
]
testnet = false
verifier = "insipx"

[[chains]]
name = 'efinity'
title = 'Efinity'
color = '#496ddb'
icon = 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/gradient/Efinity.svg'
rpc_endpoints = [
    'wss://rpc.efinity.io',
    'wss://efinity-rpc.dwellir.com',
]
testnet = false
verifier = 'insipx'

[[chains]]
name = 'enjin'
title = 'Enjin Relay'
color = '#496ddb'
rpc_endpoints = [
  'wss://rpc.relay.blockchain.enjin.io'
]
testnet = false
verifier = 'insipx'

[[chains]]
name = 'matrix'
title = 'Enjin Matrixchain'
color = '#496ddb'
rpc_endpoints = [
  'wss://rpc.matrix.blockchain.enjin.io'
]
testnet = false
verifier = 'insipx'

